### ISSUE TITLE
Should not request to solve captcha to users invited by group members

### ISSUE THREAD

**Issue by Xicnet** [J-Rios/TLG_JoinCaptchaBot#1]
Hi there  @J-Rios, we've started using your Bot within a couple Telegram groups and it seems to work fine.

We were wondering if it's possible to **skip the captcha for users invited by current group members**.

I haven't ever coded a Telegram bot, but I have experience with Python, so if you can provide some directions, I could try to help.

If you are more comfortable speaking spanish, you can send me a priv.

Thanks in advance and congratulations for your work!

**Comment by J-Rios** [comment]
Hi @Xicnet, is nice to read that you like it.

Make the Bot skip invited users is not complicated, however I won't going to add that feature to actual Bot code, cause doing it create a vulnerability that "no-users" (userbots) can uses to avoid the captcha. If I do what you ask, in groups where the option for let users invite other people is enabled:

1 - "Users" can join the group and without solve the captcha, they can invite others "users" that join without the human-test confirmation.

2 - Any bad-user or userbot that was already in the group before the captcha bot was added to it, can then invite others userbots withut the capctha confirmation.

:)

**Comment by J-Rios** [comment]
Long time ago, something what changed regarding this, now, when a user is added by an Admin of the group, then it won't be asked for captcha. If it is added by another non-admin member, then it will ask for the captcha.
