### ISSUE TITLE
Future request!!!!!

### ISSUE THREAD

**Issue by SA7BNT** [J-Rios/TLG_JoinCaptchaBot#10]
Hallo, is it possible to add a command so that the admin/admins will not become the CaptchaBot message??
Somthing like "do not send to ChatID xxxxxx 
You can get your ChatID at @FalconGate_Bot
But i guess you know that ;)

Best
Tim

**Comment by J-Rios** [comment]
Hi,

Sorry but I can't figure out what do you mean by "the admin/admins will not become the CaptchaBot message"....

Chat IDs are associated to chats (private chat, group chat, channel chat), not to users. May you are reffering to User ID? In that case, what do you mean?

**Comment by SA7BNT** [comment]
Sorry, absolut i mean the UserID :( 
Im talking about this message.
![photo_2019-07-17 18 18 06](https://user-images.githubusercontent.com/35367117/61392510-49176280-a8bf-11e9-9810-04e125a9873a.jpeg)
It should be nice if i can add my or other admins userID in the constants.py and after that i will not get this message more on my display. So the bot will block sending the added userID´s the message. 
Hope you can follow me now. :)

**Comment by J-Rios** [comment]
Ok, now I get it, however that is not Bot related and I can do nothing about that.

That is telegram client app notifications for that group, Bot does not send that message to you, it is generated by your own telegram app and it shows up notifications for all group members messages.

You can disable all notifications of the group in group options, but there is no way to just disable notifications of one specific user of a group, unless Telegram implements an option in the App to do that.

**Comment by SA7BNT** [comment]
Yea the Notifications are from the Telegram Client, but the text for the Telegram Clients Notification is comming from the bot or am i wrong? 
![Bildschirmfoto 2019-07-17 um 19 31 54](https://user-images.githubusercontent.com/35367117/61397201-a2848f00-a8c9-11e9-9dac-1622bfcaecae.JPEG)
This will be a Notification text for Telegram Clients App Notification. 
It was this text i mean.

**Comment by J-Rios** [comment]
The message is sent from the Bot to the group, not to you, also, there is no way to hide (dont show) a group message to specific users.
