### ISSUE TITLE
[Request] Customizable non-text messages restriction time

### ISSUE THREAD

**Issue by SA7BNT** [J-Rios/TLG_JoinCaptchaBot#102]
Is it possible to add

[https://github.com/J-Rios/TLG_JoinCaptchaBot/blob/c81215ed685e5d099406cea9355bef330c05b5fb/sources/constants.py#L181](url)
`    "T_SECONDS_IN_A_DAY": 86400,`

with custum days to --env / settings.py to run it when docker/py starts up?

**Comment by J-Rios** [comment]
Sure, I will check it.

## Current context

"T_SECONDS_IN_A_DAY" is a constant of number of seconds in 1 day, used to set how many time a new user will be restricted to send non-text messages in a group when "/restrict_non_text" is enabled.

## Request

Allow configure this constant through environment variable to set a different restrict time.

**Comment by J-Rios** [comment]
Modified this constant name from "T_SECONDS_IN_A_DAY" to "CAPTCHABOT_T_RESTRICT_NO_TEXT_MSG", added it to settings file and it should be updated from environment variables...

You should pass it through Docker by:

```bash
cd docker
sudo make force
sudo docker run -d --name captcha-bot -e CAPTCHABOT_TOKEN="XXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" -e CAPTCHABOT_T_RESTRICT_NO_TEXT_MSG=30 --restart always captcha-bot
```

Please test it.

**Comment by J-Rios** [comment]
## WARNING

I didn't notice until now that Telegram just allow to restrict for full days and 1 day minimum, so valid "CAPTCHABOT_T_RESTRICT_NO_TEXT_MSG" values are just 86400 multiples:

```text
86400, 172800, 259200, 345600, 432000...
```

Any other value is invalid and will cause the restriction not being applied.

I will change this constant again to handle "days" instead seconds...

**Comment by SA7BNT** [comment]
...so right now the "CAPTCHABOT_T_RESTRICT_NO_TEXT_MSG" values is not active ?? Or just use the multiples for days, like 864000 = 10 days ?

**Comment by J-Rios** [comment]
It is available right now, just make sure to use day seconds multiple as you said.

However, I will change it (maybe in a few days or next weekend) to use "number of days" instead "seconds", to avoid posible problems regarding invalid values provided.

**Comment by J-Rios** [comment]
Seems that I was wrong, Telegram doesn't need full days restriction values, it allows restriction in custom second, just as we have right now, so there is  no need to change nothing and we can use any value, but we just need to know what Telegram said about this:

> If user is restricted for more than 366 days or less than 30 seconds from the current time, they are considered to be restricted forever.

So just make sure that "CAPTCHABOT_T_RESTRICT_NO_TEXT_MSG" value must be in range 30 to 31622400.

Closing now, regards.
