### ISSUE TITLE
Resolve time bug

### ISSUE THREAD

**Issue by SiDronee** [J-Rios/TLG_JoinCaptchaBot#110]
# Initial captcha solve time (in minutes)
    "CAPTCHABOT_INIT_CAPTCHA_TIME_MIN": 2,
    
Settings say 2.. but it keeps on 5 minutes.
Tried multiple ./kill and ./run but no fix 
![image](https://user-images.githubusercontent.com/59602143/125996200-eb319db8-c7d6-426d-a736-0d357e68cd8b.png)

**Comment by J-Rios** [comment]
Hi,

Note that this constant is the default value that will be used as initial configuration in a new Telegram group. If the Bot was in the group and the Bot already have group configurations, it won't overwrite the group configuration.

Are you sure about what are you looking for? Do you know that you can configure the captcha solve time value in each group by using Bot /time command right?

Are you trying to remove Bot configuration file (data/chats/CHAT_ID) of that group before try the change? Or did you try to add the Bot to a new group?

Regards.

**Comment by sboscu** [comment]
Thanks, i did the setting inside setting.py but indeed the /time command worked! I tought it was a setting for all chats the bot are in!

**Comment by SiDronee** [comment]
You are totally right, thanks!  Problem has been solved by that!  I thought it was an overall setting and /time was just temp
