### ISSUE TITLE
[Question] Two welcome messages - how to leave just one?

### ISSUE THREAD

**Issue by DanyGee** [J-Rios/TLG_JoinCaptchaBot#111]
Hi 👋🏻 
Currently I have two welcome messages.
How to disable the first (older) one properly?
(its in Polish, but you get the idea)
![Screenshot from 2021-07-17 08 07 35@2x](https://user-images.githubusercontent.com/26818551/126027745-3706659b-3837-4d9a-97d1-1580921220be.png)

**Comment by J-Rios** [comment]
Hi,

The first message that you show in the image is the default captcha solve message that the Bot send when a user solve the captcha, and it can't be removed/modified.

Long time ago, [there was a poll](https://github.com/J-Rios/TLG_JoinCaptchaBot/issues/4) where I ask how users want to implement the custom welcome message, options was: replace the current captcha solve message with the custom welcome message one, send a new welcome message before the capchta solve message, or send it after the solve message. The result of the poll was to implement a custom welcome message that will shows up after the default one when the captcha was solved and that was done.

So currently, you just can disable your custom welcome message, not the other. To do that, you must use the command:
/welcome_msg disable

Regards.
