### ISSUE TITLE
Webhook problem

### ISSUE THREAD

**Issue by SiDronee** [J-Rios/TLG_JoinCaptchaBot#113]
I tried to set up the webhook with the following: 
the certs are created with the example given in the README section. 

> "WEBHOOK_HOST": "[public  ip off the server]",
> "WEBHOOK_PORT": 8443,
> "WEBHOOK_CERT" : SCRIPT_PATH + "/cert.pem",
> "WEBHOOK_CERT_PRIV_KEY" : SCRIPT_PATH + "/private.key",

====== ERROR Log =====

> 2021-07-17 10:45:43,407 - apscheduler.scheduler - INFO - Scheduler started
> 2021-07-17 10:45:43: Bot setup completed. Bot is now running.
> 2021-07-17 10:46:08,265 - tornado.general - WARNING - SSL Error on 8 ('91.108.6.146', 54456): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)
> 2021-07-17 10:46:08,284 - tornado.general - WARNING - SSL Error on 8 ('91.108.6.146', 54464): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)
> 2021-07-17 10:46:09,314 - tornado.general - WARNING - SSL Error on 8 ('91.108.6.146', 54714): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)
> 2021-07-17 10:46:11,315 - tornado.general - WARNING - SSL Error on 8 ('91.108.6.146', 55188): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)
> 2021-07-17 10:46:13,316 - tornado.general - WARNING - SSL Error on 8 ('91.108.6.146', 55638): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)
> 2021-07-17 10:46:15,315 - tornado.general - WARNING - SSL Error on 8 ('91.108.6.146', 56032): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)
> 2021-07-17 10:46:17,314 - tornado.general - WARNING - SSL Error on 8 ('91.108.6.146', 56436): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)
> 2021-07-17 10:46:19,315 - tornado.general - WARNING - SSL Error on 8 ('91.108.6.146', 56866): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)
> 2021-07-17 10:46:21,315 - tornado.general - WARNING - SSL Error on 8 ('91.108.6.146', 57386): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)
> 2021-07-17 10:46:23,314 - tornado.general - WARNING - SSL Error on 8 ('91.108.6.146', 58118): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)
> 2021-07-17 10:46:25,316 - tornado.general - WARNING - SSL Error on 8 ('91.108.6.146', 58722): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)
> 2021-07-17 10:46:27,316 - tornado.general - WARNING - SSL Error on 8 ('91.108.6.146', 59298): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)
> 2021-07-17 10:46:29,314 - tornado.general - WARNING - SSL Error on 8 ('91.108.6.146', 59780): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)
> 2021-07-17 10:46:31,314 - tornado.general - WARNING - SSL Error on 8 ('91.108.6.146', 60226): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)
> 2021-07-17 10:46:33,315 - tornado.general - WARNING - SSL Error on 8 ('91.108.6.146', 60898): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)
> 2021-07-17 10:46:35,314 - tornado.general - WARNING - SSL Error on 8 ('91.108.6.146', 33142): [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)
> 2021-07-17 10:46:36,788 - telegram.ext.updater - INFO - Received signal 15 (SIGTERM), stopping...
> 2021-07-17 10:46:36,788 - apscheduler.scheduler - INFO - Scheduler has been shut down
> Bot Threads end

**Comment by J-Rios** [comment]
Could be something related to bad certificate creation or maybe something regarding SSL in your machine... Did you sign them for the corresponding host IP (make sure your host public IP doesn't change)? Did you sign for enough time (years)?

You can try to generate certificates using the next script that automate the process, just change the passphrase (it is like a password for the certs) and sign information (language, location, city and company):

https://gist.github.com/J-Rios/8e015ce5a2a0d37d97e2fd652bafe790

Something like:

```bash
# Download the script
wget https://gist.githubusercontent.com/J-Rios/8e015ce5a2a0d37d97e2fd652bafe790/raw/e7852b24e83b09c23ad5e66920e371f14fde0543/create_certs

# Allow to execute
chmod +x create_certs

# Edit and modify passphrase and sign data
nano create_certs

# Execute it
./create_certs
```

**Comment by SiDronee** [comment]
I tried with the script, gets this error.
what can i check with my ssl ? 


> 2021-07-17 12:45:16: Setup Bot for Webhook.
> 2021-07-17 12:45:16,262 - apscheduler.scheduler - INFO - Scheduler started
> 2021-07-17 12:45:16,317 - telegram.ext.updater - ERROR - unhandled exception in Bot:1743403882:updater
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/telegram/ext/updater.py", line 587, in _start_webhook
>     ssl_ctx.load_cert_chain(cert, key)
> ssl.SSLError: [SSL] PEM lib (_ssl.c:3845)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/telegram/ext/updater.py", line 236, in _thread_wrapper
>     target(*args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/telegram/ext/updater.py", line 589, in _start_webhook
>     raise TelegramError('Invalid SSL Certificate') from exc
> telegram.error.TelegramError: Invalid SSL Certificate
> Exception in thread Bot:1743403882:updater:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/telegram/ext/updater.py", line 587, in _start_webhook
>     ssl_ctx.load_cert_chain(cert, key)
> ssl.SSLError: [SSL] PEM lib (_ssl.c:3845)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.7/threading.py", line 865, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/telegram/ext/updater.py", line 236, in _thread_wrapper
>     target(*args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/telegram/ext/updater.py", line 589, in _start_webhook
>     raise TelegramError('Invalid SSL Certificate') from exc
> telegram.error.TelegramError: Invalid SSL Certificate

**Comment by J-Rios** [comment]
Did you solve the issue?

I have updated the **create_certs** script to generate compatible cert and private key for CaptchaBot. Please, try to download and use it again.

**Comment by J-Rios** [comment]
Closing due no feedback.
