### ISSUE TITLE
[Question] Why not to move on GitLab?

### ISSUE THREAD

**Issue by nidamanx** [J-Rios/TLG_JoinCaptchaBot#115]
This sw is a **great one**. With a lot of potentials.
Why not to move to a real open platform like GilLab?
I think all community will approve and it will match better than to stay here.
Could be nice to think about
Thanks @J-Rios :-)

**Comment by J-Rios** [comment]
Hi,

Well, I know that Gitlab philosophy is more closer to free software ideals than Github, however Github is better known and used in general in this days, letting this software to reach a large number of people than if I host it in Gitlab.

Normally, people that use Gitlab also know and use/access Github, but there is people that just use Github and normally doesn't care of Gitlab or even doesn't know of Gitlab existance.

I see Github/Gitlab more like a GIT project hosting with some extra features, but also Github seems a little bit more like a social network where there is more interactions of people than Gitlab in general (Gitlab users are normally other developers, and less interactions occurs).

Regards.
