### ISSUE TITLE
[Question] How to set multiple custom polls captchas to verify user join a group?

### ISSUE THREAD

**Issue by toaoman** [J-Rios/TLG_JoinCaptchaBot#128]
How to set multiple custom polls to captchas when verify join a group? must answer multiple custom polls then allow join the group.

**Comment by J-Rios** [comment]
Hi,

Currently, just **one** custom poll is supported.

Configure and use of multiple polls could be added as a request for future versions...
Let me add it as Request issue:
https://github.com/J-Rios/TLG_JoinCaptchaBot/issues/129

Regards ;)
