### ISSUE TITLE
Welcome messages are not being removed / Request to make it configurable

### ISSUE THREAD

**Issue by marcopaganini** [J-Rios/TLG_JoinCaptchaBot#13]
The captcha message is correctly being deleted, but the "Welcome" message that is sent after the confirmation succeeds is not. Looking at the source (http://bit.ly/2YICmuf) it appears that there's a call to `tlg_send_selfdestruct_msg()` to do this, but it's commented out. This should be an option, hidden behind configuration.

**Comment by J-Rios** [comment]
Sure, we could create a new command to configure this and a new chat parameter to store this persistent config in each chat json file (like we do with chat language or chat captha captcha difficult level).

I'm open for PR about this, there is a lot of things that can be configurable and a lot of new functionalities that can be done, however I can't spent time in everything ;)

**Comment by AndydeCleyre** [comment]
This seems to be working fine, here's a screenshot from the audit log:

![image](https://user-images.githubusercontent.com/1787385/75697345-eec6e880-5c7a-11ea-903a-29fc2534e4a3.png)

**Comment by J-Rios** [comment]
Thanks @AndydeCleyre.

After some time, the captcha completion message behavior has been changed to be self-deleted by default too, so this issue title about "message not being removed" has lost the sense...

The issue could persist regarding to a request of make remove captcha completion message behavior configurable by users, however due it was open for long as half of year without receiving a PR, I'm going to close it now, if anyone really needs that this become configurable, feel free to open it again... 

Regards.
