### ISSUE TITLE
[Question] Can't apply custom welcome message

### ISSUE THREAD

**Issue by aleksandr-oliferuk** [J-Rios/TLG_JoinCaptchaBot#138]
Hello!

I can't change welcome message nor from bot commands, neither from data/chats/.../configs.json file. Welcome message still default.

Mine configs.json:
```
{
    "Title": "chat_name",
    "Link": "link",
    "Language": "RU",
    "Enabled": true,
    "Captcha_Chars_Mode": "nums",
    "Captcha_Time": 300,
    "Captcha_Difficulty_Level": 2,
    "Restrict_Non_Text": 0,
    "Rm_Result_Msg": true,
    "Rm_Welcome_Msg": true,
    "Poll_Q": "",
    "Poll_A": [
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    "Poll_C_A": 0,
    "Wlecome_Msg": "SOME CUSTOM TEXT",
    "Ignore_List": []
}
```

Bot version is 1.23.3 (25/09/2021)
Running on raspbian:

```
root@raspberrypi:~# lsb_release -cs
bullseye
root@raspberrypi:~# uname -a
Linux raspberrypi 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux
```

What am I do wrong?

**Comment by J-Rios** [comment]
Hi,

There is no issue in that version for config Welcome message... Maybe could be related to your system deployment...

Some Questions:

- How exactly do you change the welcome message? You should use Bot /welcome_msg command, and avoid manually edit the config file... If you manually edit the config file, then you could add some bad JSON format into it.
- Have you check Bot output.log file to see if there is any error when you try to configure the Welcome message?
- Is the directory where you have the Bot with File System write permissions? Maybe the Bot can't edit the config files if you have applied some restriction to that directory or files...
- How do you run the Bot? Are you deploying inside a virtual enviroment or using Docker?
- Is everything else working ok with the Bot? Captcha process and other commands configurations?

Best Regards.

**Comment by aleksandr-oliferuk** [comment]
Hi,

Thanks for your reply!

- When I tryed _/welcome_msg_ command, content of configs.json changes correctly - I could see my message, so problems with write permissions are ok.
- I run bot as systemctl unit directly in system (system info is in my first message).
- All other functions working fine. Below is output.log, when new user connecting:
`
2021-11-23 12:19:13: Bot started.
2021-11-23 12:19:14: Resources initialized.
2021-11-23 12:19:14: Last session data restored
2021-11-23 12:19:14: Setup Bot for Polling.
2021-11-23 12:19:14,028 - apscheduler.scheduler - INFO - Scheduler started
2021-11-23 12:19:14: Bot setup completed. Bot is now running.
2021-11-23 12:28:12: [-669172645] New join detected: @Unknoowned (634015392)
2021-11-23 12:28:13: [-669172645] Sending captcha message to @Unknoowned: 5056...
2021-11-23 12:28:13: [-669172645] Captcha send process complete.
`
The user still receives the default welcome message, although the chat settings say `"Welcome_Msg": "777"`
I tried to do `systemctl stop bot; systemctl start bot`, but with no any effect.

**Comment by J-Rios** [comment]
> The user still receives the default welcome message

Well, maybe here is the confussion, there is no a "default welcome message", there is a captcha message that can't be modified, and after captcha is solved, then the custom welcome message appears. Also, the welcome message is automatically removed after a while (1 min or so), if the /remove_welcome_msg is enabled (default).

Check if when user solve the captcha, your custom welcome message appear at this time...

**Comment by aleksandr-oliferuk** [comment]
I get it now, thank you!
