### ISSUE TITLE
[Request] Configurable welcome message deletion time

### ISSUE THREAD

**Issue by toxi22** [J-Rios/TLG_JoinCaptchaBot#155]
Is it possible to set a different value than 1 minute? For example, 5 minutes, 10 minutes (how is it done with captcha)?
Since, if the user has a slow Internet, then the chat correspondence is displayed with a long delay, more than 1 minute in the flesh and the user does not have time to see the welcome message. I have personally experienced this several times.

By default, leave 1 minute, but allow the administrator to change this value through the bot settings.

**Comment by J-Rios** [comment]
Request implemented.

Added support to configure the welcome message automatic deletion time:
https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/423dada7ce1a974567cf8e6f6cc2b7256a521b1a

This functionality will be available on current deployed Bots on next Bot version update (maybe after a couple of weeks).
Then, you will be able to configure the welcome message time through the command /welcome_msg_time.

Examples:

Delete welcome message after 30 seconds:
/welcome_msg_time 30 sec

Delete welcome message after 5 minutes:
/welcome_msg_time 5 min

Delete welcome message after 1 minute:
/welcome_msg_time 1 min

**Comment by J-Rios** [comment]
Finally, deployed @join_captcha_bot and @pro_join_captcha_bot bots has been updated to the new version that includes this new functionality. Now you should be able to configure the welcome message delete time on each group through the /welcome_msg_time command. Please check it and give some feedback.

Have a nice day.

**Comment by hpsaturn** [comment]
mmm forget this. I notice that my /connect session maybe was over. I reconnected it and it works.
