### ISSUE TITLE
[Request] Add Heroku deploy support

### ISSUE THREAD

**Issue by kucingpulung** [J-Rios/TLG_JoinCaptchaBot#165]

**Comment by J-Rios** [comment]
I have [made some changes](https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/cecd72b822a9465f5294dfd771f32b9f1cf1067f) in the code to avoid any need to modify the joincaptchabot.py file.

Now, the setup to use Heroku should only require to modify the next configurations in the settings.py file (or provide it as environment variables):

# Bot Webhook Host address
"CAPTCHABOT_WEBHOOK_HOST": "https://<appname>.herokuapp.com/",

# Bot Webhook Host Port
"CAPTCHABOT_WEBHOOK_PORT": os_environ.get("PORT", "80"),

# Bot Webhook Certificate (must be None for Heroku)
"CAPTCHABOT_WEBHOOK_CERT" : None,

# Bot Webhook Certificate private key (must be None for Heroku)
"CAPTCHABOT_WEBHOOK_CERT_PRIV_KEY" : None,

# Optionally, to verify request from Telegram Server
# (don't use the Bot Token, for security reason it must be other)
"CAPTCHABOT_WEBHOOK_SECRET_TOKEN" : None,

I don't have a Heroku account, so this is not tested, and could be nice is someone can confirm that this is enough.

Best Regard :)

**Comment by J-Rios** [comment]
Folow this support in next discussion:

https://github.com/J-Rios/TLG_JoinCaptchaBot/discussions/182
