### ISSUE TITLE
[Report] Missing Ban support in all captcha modes

### ISSUE THREAD

**Issue by ippocratis** [J-Rios/TLG_JoinCaptchaBot#173]
I saw this
https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/53c02791e7be5608605c77d6b574414f4e328bc7
Is this droped?
It supposed to ban a user after 3 unsuccessful captcha solves and kicks
I use a custom captcha (poll) and looks like my test acount can have unlimited false solves and never gets banned

**Comment by J-Rios** [comment]
Thanks for reporting.

Seems it is just supported in the normal image captcha mode and missing in other modes like the poll mode.

https://github.com/J-Rios/TLG_JoinCaptchaBot/blob/128a57f109d88b35002ed5fdd711437b9c55ea16/sources/join_captcha_bot.py#L3048-L3053

**Comment by ippocratis** [comment]
So the limit for the image capcha is 5 wrong solves?
It would make sense to lower the wrong answers limit for polls as it maxes to 6 poll options
Or maybe increase  the number of options?

**Comment by J-Rios** [comment]
Yep, maybe 3 tries of wrong answers and increase the poll options could be a good way.

**Comment by J-Rios** [comment]
Ok, some change has been done for fixing this.

https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/13f8ec3bfc72d03c7e31420330a9e49002a2ddf7

Now the Bot should be able to Ban an user in all the captcha modes, including "poll" mode, and reduced the Ban to 3 fails in poll.

Please, test it again and verify if it is working properly ;)

**Comment by ippocratis** [comment]
It now bans the user in poll mode after 3 incorrect answers
