### ISSUE TITLE
[Request] Disallow to write messages in poll and button captchas

### ISSUE THREAD

**Issue by J-Rios** [J-Rios/TLG_JoinCaptchaBot#175]
# Disallow to write msg in poll and button captchas

## Description

New members that join a group shouldn't be able to write messages after it completes the captcha when the captcha mode is "poll" or "button".

A Telegram write permission restriction should be applied to the new members when this captcha modes are used and only be removed after the captcha is completed or the user is kicked/banned.

## Context

Currently captcha modes "button" and "poll" allows new join members to write messages in the group before the captcha is completed. This behaviour comes from the image based captcha modes where it is intended to allow write this messages because it is required for solving the captcha, and also to allow the user ask to other group members about how to solve the captcha in case the user is not familiar with them.

Captchas modes "poll" and "button" are enough simple and understandable that is it completely fine to restrict the write of messages in this modes.

**Comment by J-Rios** [comment]
Request implemented.

https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/3bc73e3ddf53ccecc3371a69da81126237267679

Now the new members that join a group are restricted to send not required messages before captcha verification.

**Comment by sharuzzaman** [comment]
this feature has a bug.

I noticed if I use hex or ASCII, the user cannot type the answer to the captcha.

when I change the mode to nums, the user can type the answer.

```
        # Restrict user to deny send any kind of message until captcha is solve
        # Allow send text messages for image based captchas (nums and maths)
        if (captcha_mode == "nums") or (captcha_mode == "math"):
            # Restrict user to only allow send text messages
            tlg_restrict_user(bot, chat_id, join_user_id, send_msg=True,
                send_media=False, send_stickers_gifs=False, insert_links=False,
                send_polls=False, invite_members=False, pin_messages=False,
                change_group_info=False)
        else:
            tlg_restrict_user(bot, chat_id, join_user_id, send_msg=False,
                send_media=False, send_stickers_gifs=False, insert_links=False,
                send_polls=False, invite_members=False, pin_messages=False,
                change_group_info=False)
```

**Comment by J-Rios** [comment]
Should be fixed now with this changes:

https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/675c03f6a828ddd452266a404830ce5d5f270627

Please check it.
