### ISSUE TITLE
[Bug] Captcha is not sent when hide members is active

### ISSUE THREAD

**Issue by selankon** [J-Rios/TLG_JoinCaptchaBot#180]
New Telegram versions have the ability to activate an option called "hide members". 

I observed that apparently the bot stops working, probably the new user event is hidden. Is there any workaround to fix this? 

The new users message appear on the group last activity, but not the messages that the capchabot  should send.

Any suggestion of way to fix this via PR?

**Comment by J-Rios** [comment]
Hi, thanks for notifying!

Can you check if the Bot is an Administrator of the group? and which permissions it has?

Regards

**Comment by selankon** [comment]
Is admin with all permissions unless remain anonymous and add other admins

**Comment by selankon** [comment]
Is self hosted, maybe i need to update it to last stable version i will try asap

**Comment by J-Rios** [comment]
You can find the latest version of the Bot in the **development** and **public** branches (it was in testing, but everything seems to be fine, so it could be considered stable, I just haven't had time to update the master and private branches yet) and this version uses the new python-telegram-bot v20 version.

Remember that new telegram features support also requires to update python-telegram-bot:

```bash
python3 -m pip install -r TLG_JoinCaptchaBot/requirements.txt
```

**Comment by selankon** [comment]
I tried to upgrade it to public_limited and the bot left my own room for the limit of users... 

What branch should I use better, development or master?

**Comment by J-Rios** [comment]
Development, It has no restriction.

**Comment by selankon** [comment]
Ok I supose this will work as expected because the bot reacted to a new access. ASAP I'm sure is working on hidden user list I will close the issue, thanks a lot

**Comment by selankon** [comment]
This is working well, thanks for help
