### ISSUE TITLE
The run script outputs Not running

### ISSUE THREAD

**Issue by ssmlee04** [J-Rios/TLG_JoinCaptchaBot#30]
follow the install page and changed the token as well. But when I do `./run` it outputs `Not running.`. Does anyone know what I should do? 

My pillow version is `6.2.0`. Python is `2.7.12`

**Comment by J-Rios** [comment]
Hi,

The statement "Not running" means that the execution fail, you can **check the cause looking inside the generated output.log file**.

If you take a look into the run script you can see that it tries to run it with python3, so if you want to use python2 then you need to change it or run it manually (without the script), however I recommend you to just **upgrade and use actual python3** version instead, a lot of Bot changes has been done after the last time that I try python2 on it, so **python2 support could be broken** (and don't expect support for it, python2 has been deprecated).

P.D. Remember that you will need to install requeriments.txt for python3 (use the pip of python3 instead python2).

Regards.

**Comment by ssmlee04** [comment]
Got it. Thanks turns out it's not able to find module `telegram`. Solved by using pip3 to install all the modules. Thanks.
