### ISSUE TITLE
Improve the translation of a language

### ISSUE THREAD

**Issue by Ivans-Git** [J-Rios/TLG_JoinCaptchaBot#31]
The language I selected (Galician) has some errors and I would like to improve it, what is your translation platform?

**Comment by J-Rios** [comment]
Hi,

I have added some language contribution instructions in Readme file...

Actual language support is based on external JSON files that contains all bot texts for each language, so you just need to modify the [Galician file](https://github.com/J-Rios/TLG_JoinCaptchaBot/blob/master/sources/language/gl.json).

**Comment by Ivans-Git** [comment]
> Hi,
> 
> I have added some language contribution instructions in Readme file...
> 
> Actual language support is based on external JSON files that contains all bot texts for each language, so you just need to modify the [Galician file](https://github.com/J-Rios/TLG_JoinCaptchaBot/blob/master/sources/language/gl.json).

If I modify it and save it, are the changes already applied?  something else i have to do?

**Comment by J-Rios** [comment]
Due it is an existing and supported language, that's all, just modify the file.
