### ISSUE TITLE
Are command hints translatable?

### ISSUE THREAD

**Issue by DanyGee** [J-Rios/TLG_JoinCaptchaBot#43]
Hi,
are those translatable?
![Capture+_2020-05-19-07-36-09](https://user-images.githubusercontent.com/26818551/82292394-20fb0300-99ab-11ea-99c1-f81b719fccc7.png)
If not, any chance, that they will be?

**Comment by J-Rios** [comment]
Hi,

Commands hints comes from Bot account configuration (@BotFather), it is not related to Bot source code, and Telegram doesn't support multiple languages hints. So there is no way right now and it all depends on Telegram.

Regards.

**Comment by DanyGee** [comment]
THX for clarification!
