### ISSUE TITLE
[Request] Make Bot to just response commands to Admins

### ISSUE THREAD

**Issue by SA7BNT** [J-Rios/TLG_JoinCaptchaBot#47]
Can it be possible to add a command / funktion in the constants.py that the bot just answer commands from the admins in the group? 
If 200 user testing the command /help it is very *piiiiiiiiip* ;) 

Best

**Comment by J-Rios** [comment]
About actual behavior:
- The Bot response in groups to any user (not just Admins), when they execute some commands like **/start /help /commands** and **/about** commands.

Requesting:
- Get Bot to response this commands only for group Admins executions.

Notes:
- Commands response to any user gives useful Bot usage information. Due this, It is better to create a new Bot command to enable/disable commands response in specific group, instead disable response in all groups.

**Comment by J-Rios** [comment]
Done, now the Bot just response commands to Admins of a group by default.
