### ISSUE TITLE
[Request] Make bot private to certain groups only

### ISSUE THREAD

**Issue by sharuzzaman** [J-Rios/TLG_JoinCaptchaBot#52]
I would like to host the bot for several groups that I manage and would like to have the bot only responding or can be added to a certain group only.

This StackOverflow post have hint to how to control the bot: https://stackoverflow.com/questions/46015319/how-to-make-a-private-telegram-bot-accessible-only-by-its-owner

If you can help show where the bot determines the channel it joins, I can try to figure out how to limit the bot. Or someone else with better Python expertise can help as well

Thank you.

**Comment by J-Rios** [comment]
Bot Private support has been implemented.
Also added instructions in README about this new characteristic :)
