### ISSUE TITLE
[Bug] Bot doesn't delete "joined the group" message

### ISSUE THREAD

**Issue by Nihisil** [J-Rios/TLG_JoinCaptchaBot#53]
I'm sure that the bot deleted "joined the group" message before when spammer wasn't able to solve the captcha.

In the latest version this message remaining in the channel.

![image](https://user-images.githubusercontent.com/475367/86423669-f96db900-bd12-11ea-9332-bb54954b3d9a.png)

**Comment by J-Rios** [comment]
Will be fixed this weekend ;)

**Comment by J-Rios** [comment]
Ok, this has been fixed, now again the user join message will be deleted too in 5 mins after a user fail to resolve the captcha.

**Comment by Nihisil** [comment]
Thank you!
