### ISSUE TITLE
[Question] Does @join_captcha_bot support other variables rather than just $user? As shown in the tip message.

### ISSUE THREAD

**Issue by K0media** [J-Rios/TLG_JoinCaptchaBot#55]
I'd like to know if your bot supports more placeholders other than `$user`. That way I can customize the welcome message even more.

If there are more placeholders and tricks, I'd really be glad if that could be added to the help documentation.

Thanks.

**Comment by J-Rios** [comment]
Hi,

Actually just support for $user is implemented.

Regards.
