### ISSUE TITLE
[Request] Inherit markdown formatting from original message on /welcome_msg set-up

### ISSUE THREAD

**Issue by K0media** [J-Rios/TLG_JoinCaptchaBot#57]
I noticed that the welcome message won't be set up as the same formatting as we format in the normal markdown form.

The break lines, underscores, bold, italic, etc, won't be inherited to the normal formatting.

Probably what you have in mind with the welcome message is something brief, but detailing more for lay people that barely understand how Telegram works would be a bit better.

I've set it up along with Rose to explain what should be done, after all there are many people that join Telegram to ask a few things and drop out right after some days or weeks.

Can that be done?

Expected behavior:

![image](https://user-images.githubusercontent.com/22375465/86961263-4ac4e080-c137-11ea-965f-43006347c7a3.png)

Current behavior:

![image](https://user-images.githubusercontent.com/22375465/86961338-71831700-c137-11ea-9b9c-6607b168250c.png)

Thanks.

**Comment by J-Rios** [comment]
Done, current Bot account will be updated with this in a few hours.
