### ISSUE TITLE
[Request] Add a way to unban a users

### ISSUE THREAD

**Issue by luzfcb** [J-Rios/TLG_JoinCaptchaBot#59]
I mistakenly banned a user and found no simple way to undo the operation or get a list of users blocked or removed from the group.

https://www.reddit.com/r/Telegram/comments/6z9p2c/comment/dmujzpp

**Comment by J-Rios** [comment]
## About actual behavior:

- The Bot Ban users if they fail 5 times to solve the captcha in the same group.
- Then, admins are notified about the Ban and tell that they need to manually unban the user in group settings.
- There is no way to unban users through nthe Bot.

## Requesting:

- Add some command/s to list ban users and unban any of them through the Bot.

## Notes:

- To know wich users are banned in the group, we should use Telegram API and request for that information instead store user data (avoid store user data is a must).

**Comment by J-Rios** [comment]
Nearly two years have passed without any developer interested on implement this, and due the JoinCaptchaBot could be considered a Bot for group access and not for moderating groups, I'm going to close this request. If anyone is interested on developing it, feel free to write here or open this issue again to talk about it.

Regards.
