### ISSUE TITLE
[Question] How to mute the user before he solve the captcha?

### ISSUE THREAD

**Issue by AronWater** [J-Rios/TLG_JoinCaptchaBot#60]
user could still send something in group before verifying.  How to mute them before they have complete the captcha task?

**Comment by J-Rios** [comment]
The Bot didn't support to mute users before captcha completion.

There is some reason why it has not been done:

- If you mute all new users, then they can't send message to solve the captcha.
- If a user has problems in understanding how to solve the captcha, he can ask to other group users about it, if we mute the user then he can ask for help.
