### ISSUE TITLE
[Request] Delete all messages from new users

### ISSUE THREAD

**Issue by Stezkoy** [J-Rios/TLG_JoinCaptchaBot#64]
How to delete all messages from new users?
There are bots that immediately reset the ad when it enters.
Can I get the bot to quickly delete all messages from a user who didn't pass the captcha?

**Comment by J-Rios** [comment]
Hi,

Current Bot didn't support to remove all messages from users that doesn't solve the captcha.

Let me explain with an example, one of the reason of why it is not implemented:

- A new human user enter the group.

- This person doesn't understand the captcha and what he have to do, so he ask to other group members about it.

- At this moment there is not active users in the group, so the new user is kicked from the group.

- Now, if the messages requesting for help from this user was also removed as you request, nobody notice that a new user can't solve the captcha. Instead, if the messages remains, then other users and Admins of the groups can notice that and bring help to that user from private chat or when he try to join again.

However, a PR with new Bot optional functionality, disabled by default, that can be enabled in specific groups through a new command, to enable Bot remove all new users kicked messages in that group, can be accepted.

**Comment by Stezkoy** [comment]
Is it possible to implement, at least on a button, deleting all messages?

**Comment by J-Rios** [comment]
Duplicated in:
https://github.com/J-Rios/TLG_JoinCaptchaBot/issues/120

Let's close this one and use the other issue regarding this.
