### ISSUE TITLE
docker pull

### ISSUE THREAD

**Issue by SA7BNT** [J-Rios/TLG_JoinCaptchaBot#74]
Hallo, what am i missing??

> sudo docker pull captcha-bot
Using default tag: latest
Error response from daemon: pull access denied for captcha-bot, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by J-Rios** [comment]
Hi, there is no docker base image of captcha-bot published in Docker Hub, so you can't just pull it... The instructions about Bot Docker usage specify the way to create a new docker container and use it:
https://github.com/J-Rios/TLG_JoinCaptchaBot/blob/master/docker/README.md

**Comment by SA7BNT** [comment]
If i create a new container from project sources whats about the config from the old JoinCaptchaBot?? May i start from zerro again??
