### ISSUE TITLE
[Bug] Bot unrestrict already banned users when kicking

### ISSUE THREAD

**Issue by kokizzu** [J-Rios/TLG_JoinCaptchaBot#75]
I was banning some spam bot account before (because i administrating multiple group, so i know which one) they responding the captcha
![image](https://user-images.githubusercontent.com/1061610/99894534-3e40bf00-2cb7-11eb-9aa4-02f57f1c0b69.png)

but everytime the join captcha bot banned the spammy bot account, it always add their permission back
![image](https://user-images.githubusercontent.com/1061610/99894525-29642b80-2cb7-11eb-8faf-c200717e5b70.png)

which is counter-productive

**Comment by J-Rios** [comment]
Hi,

Some info: the reason for Bot unrestrict users is that Telegram doesn't provide a "just kick" request, it only allows Ban and it automatically restrict the user, so to make a "just kick" without restrict the user, is necessary to unrestrict the kicked user.

That was why, however, it seems that last changes in Bot code [doesn't check if the user is already out of the group before unrestrict](https://github.com/J-Rios/TLG_JoinCaptchaBot/blob/1f602edc8b52798a4c6f9221f305831cbfce02a5/sources/tlgbotutils.py#L176), so it can actually be considered a bug. Let me fix this for next update :)

Best Regards.

**Comment by J-Rios** [comment]
Ok, so [should be fixed](https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/3f5a32ab2237df97bf38878d66cb4101935c1188) now.
