### ISSUE TITLE
Clarify the meaning of kick and ban

### ISSUE THREAD

**Issue by ignaciolep** [J-Rios/TLG_JoinCaptchaBot#8]
Please, clarify the meaning of kick and ban so non-techie users can understand. Putting the definition in parentheses should be enough.

Example in Spanish:
- kickeado (echado)
- baneado (bloqueado)

_Originally posted by @ignaciolep in https://github.com/J-Rios/TLG_JoinCaptchaBot/pull/3#issuecomment-502109011_

**Comment by J-Rios** [comment]
Se ha procedido a sustituir en los mensajes en español, los terminos y conjugaciones "kick" y "ban", por su significado, mientras que se mantiene entre paréntesis los terminos "técnicos" kick/ban. Así todo el mundo debería de ser capaz de comprender que significa.

Por favor, no me vengais ahora con que hay que traducir los terminos "Spam" o "Captcha" ;)
