### ISSUE TITLE
Docker image not working 

### ISSUE THREAD

**Issue by wolverine810** [J-Rios/TLG_JoinCaptchaBot#83]
Maybe the docker image is using an older version of pillow.

**Comment by J-Rios** [comment]
It could have broken since new Bot settings changes...

I mean, related to this:

https://github.com/J-Rios/TLG_JoinCaptchaBot/pull/69

https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/1f602edc8b52798a4c6f9221f305831cbfce02a5

**Comment by J-Rios** [comment]
Docker image build fix and checked deployment and usage specifying environment variables, seems that everything works ok now. 

Take a look into:
https://github.com/J-Rios/TLG_JoinCaptchaBot/pull/87

Closing the issue.
