### ISSUE TITLE
Delay before sending captcha

### ISSUE THREAD

**Issue by FriendlyNeighborhoodShane** [J-Rios/TLG_JoinCaptchaBot#86]
When a user joins a group with "Show history for new members" disabled, the bot is sometimes too quick to send the captcha, such that it isn't even visible to the new user.

This is most probably a bug on Telegram's side, but it would be useful to add a delay (~2-5 seconds) between recieving the event from telegram and sending a captcha.

Thanks for the great bot!

**Comment by J-Rios** [comment]
Hi,

I see your point, but I'm affraid doing that change increase a lot the resources needed by the Bot to handle the delays without affecting general Bot response time (due it can't be done inside the received telegeram event handler, it should be stored and manage independently), so is not acceptable to make that change.

If the Bot is going to be used in few groups (less than hundred), it can be accepted, but not for a Bot running in thousands of groups.

Regards.

**Comment by FriendlyNeighborhoodShane** [comment]
I think just adding a `time.sleep(2)` statement at line 593 of join_captcha_bot.py would be sufficient for this. Since the receiver runs async anyway.

**Comment by FriendlyNeighborhoodShane** [comment]
Actually NVM, we don't require this anymore, so unless this is something that you want to pursue, I'll close it.
