### ISSUE TITLE
[Request] Delete all non-text messages for new unverified members

### ISSUE THREAD

**Issue by tttmmmsss** [J-Rios/TLG_JoinCaptchaBot#88]
The /help and /commands say that only images sent are automatically deleted by the bot, no muting or other restrictions are put on a new unverified user since the bot does the message deleting automatically.

1. Does the bot delete those images instantly, or is there a delay?

2. Can it be set to delete ALL non-text messages, including gifs, videos, and stickers, or is that already implemented and just not stated anywhere?

Thank you

**Comment by J-Rios** [comment]
Some messages are deleted and some others not, some have a delay and some are deleted instantly...

- Bot commands response messages are removed after some time delay (5 mins).
- Captcha images are deleted instantly when the users solves them or when time to kick has reach without solved.
- Captcha result information messages (the msgs that tells if the user solves or fail to resolve the captcha) are removed after some time delay (5 mins).
- Non-text media messages (images, stickers, gif, audio, etc.) sent by users when they are in captcha process are considered Spam and instantly removed. Maybe this is your second question, if so, you are right, it is implemented but maybe there is missing regarding that behavior in help command information.

Best Regards.

**Comment by tttmmmsss** [comment]
Thank you that is very clear and answers all my questions!
