### ISSUE TITLE
Deleting messages not working with forwarded messages

### ISSUE THREAD

**Issue by JuanjoSalvador** [J-Rios/TLG_JoinCaptchaBot#9]
Related: #5 

When someone forward any message before be kicked from the group, that message is not deleted too.

**Comment by showTi** [comment]
Related: #5

When someone forward any message before be kicked from the group, that message is not deleted too.

 @showTi

**Comment by J-Rios** [comment]
Seems that this was fixed at some point in the past.

Closing issue now, feel free to re-open if the problem still persists. In that case, please shows steps to reproduce.

Regards.
