### ISSUE TITLE
LANG_CHANGE message suggestion

### ISSUE THREAD

**Issue by dakeshi** [J-Rios/TLG_JoinCaptchaBot#93]
in language file,

>     "LANG_CHANGE": "Language changed to English.",

With this constant message structure, a bot tells us misleading result when we configure it with other lang.

## expected result
Language changed to {target_lang}

## current result
Language changed to English

**Comment by J-Rios** [comment]
## Context

Currently, the word **English** of "LANG_CHANGE" text must be translated to current language file when texts are translated.

Example: when making Korean translation, the word **English** should be translated to **Korean** in Korean language...

## Possible Fixs

To avoid mistakes when translation is done, this can be done:

- Specify that change in README translate instructions.
- Change **English** to **{target_lang}**, where target_lang is **en, es, ko, fr, etc.**
- Change **English** to **{target_lang}**, where target_lang is the language name in English language (English, Spanish, Korean, French, etc.).

**Comment by J-Rios** [comment]
Maybe we should go with **option B**, it is the more simple and avoid any future problems regarding language names (also avoid the needs to add and maintain a "language code - language name" correspondence in constants.

**Comment by dakeshi** [comment]
agree. option B looks the most simple solution

**Comment by J-Rios** [comment]
Ok, done in [this commit](https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/bf0bb1d9f31b8587fa1cca227ffa97b31d534cb9), just changed in english file for future translations and fixed in Korean.
