### ISSUE TITLE
[Request] Solve an equation to join the chat (new captcha mode)

### ISSUE THREAD

**Issue by jzvi12** [J-Rios/TLG_JoinCaptchaBot#99]
Possible for the bot to generate random equations with 3 buttons at the bottom showing possible options (one of them must be 
 the correct one)?

![telegram_resolve_math](https://user-images.githubusercontent.com/10729787/119198837-047b2600-ba58-11eb-95eb-4cbc047eaebd.png)

demo [here](https://t.me/CryptoComOfficial)

**Comment by J-Rios** [comment]
Added generation of math equation captchas to [multicolorcaptcha library](https://github.com/J-Rios/multicolorcaptcha).

New Captcha example:

![Math Captcha Example](https://github.com/J-Rios/multicolorcaptcha/raw/master/images/Math.png)

**Comment by J-Rios** [comment]
New math equation captcha mode implemented in [this commit](https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/66266fd44115c520712df6be7b61fe84cef2e67b).

I think the use of buttons to select the right answer could be considered too insecure and easy to solve for a Bot just by a random coice of a button. So it won't be implemented.
